# Generated by Django 4.1.7 on 2024-05-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("thought", models.TextField()),
                ("beliefRating", models.IntegerField()),
                ("emotion", models.TextField()),
                ("emotionIntensity", models.IntegerField()),
                ("situation", models.TextField()),
                ("distortions", models.TextField()),
                ("initialReframe", models.TextField()),
                ("finalReframe", models.TextField()),
            ],
        ),
    ]
